thresholds:
  # Maximum allowed check amount in dollars.
  amount_max: 100000

  # Minimum allowed check amount in dollars.
  amount_min: 0

  #The maximum age of a check in months before it is considered invalid.
  check_age_limit_months: 6
